name: flutter_geocoder
description: Forward and reverse geocoding.
version: 0.0.1
homepage: https://github.com/SmarttersStudio/flutter_geocoder

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0

flutter:
  plugin:
    androidPackage: com.smarttersstudio.geocoder
    pluginClass: GeocoderPlugin
